# Generated by Django 5.2.5 on 2025-08-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='map_link',
        ),
    ]
